config/routes.rb
Vupoint::Application.routes.draw do

  
  get "invitations/new"

  get "invitations/create"

  get "invitations/destroy"

  match 'users/notifications', to: 'users#notifications', as: :notifications

  match 'users/join/:id', to: 'users#join_private_conversation', as: :join_private_conversation 

  resources :users do
    member do
      get :following, :followers
    end
  end

  
  resources :invitation_requests, only: [:new, :create, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]

  resources :debates, only: [:create, :destroy, :show, :index]

  match 'debates/invitation/:id', to: 'debates#invitation', as: :invitation

  match "debates/:id/:url", to: "debates#show"
  
  match "debates/search", to: 'debates#search'

  resources :relationships, only: [:create, :destroy]

  resources :viewpoints, only: [:create, :destroy]

  resources :arguments, only: [:new, :create, :destroy, :index]

  resources :debate_invites, only: [:create, :destroy]

  match 'conversation/allow/:id', to: "debates#allow_joining_private_conversation", as: :allow_joining_private_conversation

  resources :notifications, only: :destroy

  resources :invitations, only: [:new, :create, :destroy]

  root to: 'pages#home'

  match "/help", to: 'pages#help', as: :help

  match "/tou", to: 'pages#tou', as: :terms

  match "/signup", to: 'users#new', as: :signup

  match "/signin", to: 'sessions#new', as: :signin

  match "/signout", to: 'sessions#destroy', as: :signout, via: :delete

  match "/confirm", to: 'users#confirm', as: :confirmation

  match "/invited", to: 'users#invited', as: :invited

  match "/users/search_by_name", to: 'users#search_by_name'

  match "viewpoints/publish/:id", to: 'viewpoints#publish', as: :publish, via: :put

  match 'users/:id/:url', to: "users#show"

  match '/send_invitation', to: "users#send_invitation", as: :send_invitation

  match '/stats', to: "pages#stats", as: :stats 

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  	attr_accessible :message, :classname, :unknown_object_id

  	belongs_to :user

  	validates :message, length: { maximum: 140 }

  	validates :user_id, presence: true

    default_scope order: 'notifications.created_at DESC'

    before_save :clean_up!


  	def message_tokens
  		unknown_object = Kernel.const_get(self.classname).find_by_id(self.unknown_object_id)
  		if unknown_object.nil?
  			nil
  		else
  			unknown_object.message_tokens
  		end
    end

    private
      def clean_up!
        #keep hundred notifications per user except for the admin user
        user = User.find(self.user_id)
        unless user.admin
          notifications = Notification.where('user_id = ?', self.user_id)
          if notifications.size >= 100
            notifications.last.destroy
          end
        end
      end

      def message_length
      end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	before_filter :signed_in_user

	before_filter :correct_user

  before_filter :force_mobile


	def destroy
    	@notification.destroy
    	flash[:success] = "Notification deleted!"
    	if current_user.notifications.any?
    		redirect_to notifications_path(current_user)
    	else
    		redirect_to root_path
    	end

  	end


  	private

    	def correct_user
      		@notification = Notification.find(params[:id])
      		unless current_user?(@notification.user)
	      		redirect_to root_path
	      	end
    	end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
	def get_notification_content_partial_name(notification)
		"notifications/#{notification.classname.downcase}_content"
	end

	def get_notification_actions_partial_name(notification)
		"notifications/#{notification.classname.downcase}_actions"
	end

	def get_user_from_join_request_notification(notification)
		join_request = JoinRequest.find(notification.unknown_object_id)
		join_request.user
	end

	def get_debate_from_join_request_notification(notification)
		join_request = JoinRequest.find(notification.unknown_object_id)
		join_request.debate
	end
	
end

app/views/notifications/_debateinvite_actions.html.erb
	<div class="join">
		<%= link_to "join conversation", debate_url(get_debate_from_notification(notification)) %>
	</div>

app/views/notifications/_debateinvite_actions.mobile.erb
<div class="join">
	<%= link_to "join conversation", debate_url(get_debate_from_debate_invite_notification(notification)) %>
</div>

app/views/notifications/_debateinvite_content.mobile.erb
<span class="content">

	<%="#{notification_message_tokens[0]}"%> has invited you to a <b>new conversation</b>:
	<div class="notification-core">
		"<%="#{notification_message_tokens[1]}"%>"
	</div>
	<% if notification_message_tokens[2].length > 0 %>
		message: <%= "#{notification_message_tokens[2]}" %>
	<% end %>

</span>

<div class="timestamp">
	sent <%= time_ago_in_words(notification.created_at) %> ago.
</div>

app/views/notifications/_invitationrequest_actions.mobile.erb
<div class="invite">
	<%= link_to "send invite", send_invitation_path(invitation_request: get_invitation_request_from_notification(notification), notification: notification) %>
</div>

app/views/notifications/_invitationrequest_content.mobile.erb
<span class="content">

	Request for a <b>vupnt invitation</b> by:
	<div>
		<b>Name: </b>"<%="#{notification_message_tokens[0]}"%>"
	</div>
	<div>
		<b>Email: </b>"<%="#{notification_message_tokens[1]}"%>"
	</div>
	<div>
		<b>City: </b>"<%="#{notification_message_tokens[2]}"%>"
	</div>
	
</span>

<div class="timestamp">
	sent <%= time_ago_in_words(notification.created_at) %> ago.
</div>

app/views/notifications/_joinrequest_actions.mobile.erb
<% debate = get_debate_from_join_request_notification(notification) %>
<% user = get_user_from_join_request_notification(notification) %>

<div class="invite">
	<%= link_to "view profile", user_path(user) %>
</div>

<div class="invite">
	<%= link_to "allow", allow_joining_private_conversation_path(notification) %>
</div>

app/views/notifications/_joinrequest_content.mobile.erb
<span class="content">
	<div>
		<b><%= notification_message_tokens[0]%></b> wants to join your <span class="label-private">private</span> conversation:
	</div>
	<div>
		# <%=notification_message_tokens[1]%>
	</div>
</span>

<div class="timestamp">
	sent <%= time_ago_in_words(notification.created_at) %> ago.
</div>

app/views/notifications/_notification.html.erb
<% unless notification.message_tokens.nil? %>
<li>
<%= render partial: get_notification_content_partial_name(notification),
      locals: {notification_message_tokens: notification.message_tokens,
      notification: notification }%>

    
  <div class="actions">
    <%= render partial: get_notification_actions_partial_name(notification), locals: {notification: notification }%>
    <div class="delete">
        <%= link_to "delete", notification, method:  :delete,
                                     confirm: "You sure?" %>
    </div>
  </div>
</li>
<br />
<% end %>

app/views/notifications/_notification.mobile.erb

	<% unless notification.message_tokens.nil? %>
	<li>
	<%= render partial: get_notification_content_partial_name(notification),
	      locals: {notification_message_tokens: notification.message_tokens,
	      notification: notification }%>

	    
	  <div class="actions">
	    <%= render partial: get_notification_actions_partial_name(notification), locals: {notification: notification }%>
	    <div class="delete">
	        <%= link_to "delete", notification, method:  :delete,
	                                     confirm: "You sure?" %>
	    </div>
	  </div>
	</li>
	<br />
	<% end %>

app/views/notifications/_user_actions.mobile.erb
<div class="follow">
	<%= link_to "view profile", user_path(get_user_from_notification(notification)) %>
</div>

app/views/notifications/_user_content.mobile.erb
<span class="content">
	<b><%="#{notification_message_tokens[0]}"%></b> is now following your conversations!<br />
</span>

<div class="timestamp">
	sent <%= time_ago_in_words(notification.created_at) %> ago.
</div>

app/views/notifications/_viewpoint_actions.mobile.erb
<% if !get_viewpoint_from_new_viewpoint_notification(notification).published? %>
	<div class="publish">
		<%= link_to "publish vupnt", publish_path(get_viewpoint_from_new_viewpoint_notification(notification)), method: :put %>
	</div>
<% end %>
<div class="join">
	<%= link_to "join conversation", debate_url(get_debate_from_new_vupnt_notification(notification)) %>
</div>

app/views/notifications/_viewpoint_content.mobile.erb
<span class="content">
	A <b>new vupnt</b> on your conversation:

	<div class="notification-core">
	</b><%="#{notification_message_tokens[0]}"%>: </b><%="#{notification_message_tokens[2]}"%>
	</div>


	<small># <%="#{notification_message_tokens[1]}"%></small>

	
</span>

<div class="timestamp">
	sent <%= time_ago_in_words(notification.created_at) %> ago.
</div>