config/routes.rb
Vupoint::Application.routes.draw do

  
  get "invitations/new"

  get "invitations/create"

  get "invitations/destroy"

  match 'users/notifications', to: 'users#notifications', as: :notifications

  match 'users/join/:id', to: 'users#join_private_conversation', as: :join_private_conversation 

  resources :users do
    member do
      get :following, :followers
    end
  end

  
  resources :invitation_requests, only: [:new, :create, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]

  resources :debates, only: [:create, :destroy, :show, :index]

  match 'debates/invitation/:id', to: 'debates#invitation', as: :invitation

  match "debates/:id/:url", to: "debates#show"
  
  match "debates/search", to: 'debates#search'

  resources :relationships, only: [:create, :destroy]

  resources :viewpoints, only: [:create, :destroy]

  resources :arguments, only: [:new, :create, :destroy, :index]

  resources :debate_invites, only: [:create, :destroy]

  match 'conversation/allow/:id', to: "debates#allow_joining_private_conversation", as: :allow_joining_private_conversation

  resources :notifications, only: :destroy

  resources :invitations, only: [:new, :create, :destroy]

  root to: 'pages#home'

  match "/help", to: 'pages#help', as: :help

  match "/tou", to: 'pages#tou', as: :terms

  match "/signup", to: 'users#new', as: :signup

  match "/signin", to: 'sessions#new', as: :signin

  match "/signout", to: 'sessions#destroy', as: :signout, via: :delete

  match "/confirm", to: 'users#confirm', as: :confirmation

  match "/invited", to: 'users#invited', as: :invited

  match "/users/search_by_name", to: 'users#search_by_name'

  match "viewpoints/publish/:id", to: 'viewpoints#publish', as: :publish, via: :put

  match 'users/:id/:url', to: "users#show"

  match '/send_invitation', to: "users#send_invitation", as: :send_invitation

  match '/stats', to: "pages#stats", as: :stats 

end

app/views/shared/_argument_item.mobile.erb
<li id="<%= argument_item.id %>">
    <% cache "sha_arg_1-#{argument_item.id}" do %>
    
    <h2>
      <%= link_to argument_item.user.name, argument_item.user %>
      <% if argument_item.is_up_vote %>
        <%= image_tag("thumbs_up.png") %>
      <% else %>
        <%= image_tag("thumbs_down.png") %>
      <% end %>
    </h2>

    <% end %>
  
  <div class="content">

  <% if argument_item.is_up_vote %>
    
    <% cache "sha_arg_2-#{argument_item.id}" do %>
      <div class="win-position">
        <%= argument_item.content %>
      </div>
      <span class="timestamp">
        posted <%= time_ago_in_words(argument_item.created_at) %> ago.
      </span>
    <% end %>

  <% else %>

    <% cache "sha_arg_3-#{argument_item.id}" do %>
      <div class="loss-position">
        <%= argument_item.content %>
      </div>
      <span class="timestamp">
        posted <%= time_ago_in_words(argument_item.created_at) %> ago.
      </span>
    <% end %>

  <% end %>
  
  
  <% if current_user?(argument_item.user) %>
    <% cache "sha_arg_4-#{argument_item.id}" do %>
      <div class="actions">
        <div class="delete">
          <%= link_to "delete", argument_item, method:  :delete,
                                         confirm: "You sure?",
                                          title:   argument_item.content %>
        </div>
      </div>
    <% end %>                                     
  <% end %>
</li>
<br />

app/views/shared/_debate_form.mobile.erb

	<div class="section-title">
		start a conversation!
	</div>
	<%= form_for(@debate) do |f| %>

		<%= render 'shared/error_messages', object: f.object %>

		
			<div class="row-fluid">
				<%= f.text_area :content, rows: 2 %>
			</div>
			<div class="field-desc">
			a debate, a question, or just about anything on your mind... in 140 chars or less!
			</div>
		
		<%= f.check_box :is_private %> <span class="label-private">mark as private?</span>

		<div class="row-fluid center">
			<%= f.submit "start", class: "btn btn-large btn-primary" %>
		</div>

	<% end %>

app/views/shared/_debate_item_actions.mobile.erb
  <div class="row-fluid">
  
    <div class="actions">
      
      <% if current_user?(user) %>
          
          <div class="listview">
            <%= link_to pluralize(debate.viewpoints.size, "vupnt"), debate_url(debate) %>
          </div>

          <div class="invite">
            <%= link_to "invite a friend", invitation_path(debate) %>
          </div>

          <div class="delete">
            <%= link_to "delete", debate, method:  :delete,
                                       confirm: "Delete this conversation?",
                                       title:   debate.content %>
          </div>

      <% elsif signed_in? %>

        <% if debate.is_private %>

          <% if debate.has_participant?(current_user) %>
            <div class="join">
              <%= link_to pluralize(debate.viewpoints.size, "vupnt"), debate_path(debate) %>
            </div>

            <div class="join">
              <%= link_to "leave conversation", '#' %>
            </div>

          <% else %>
              <% if join_request_pending?(debate) %>
                <div class="field-desc">
                  Your request to join this private conversation is pending!
                </div>
              <% else %>
                <div class="invite">
                  <%= link_to "request invitation", join_private_conversation_path(debate) %>
                </div>
              <% end %>
          <% end %>

        <% else %>
          <div class="listview">
            <%= link_to pluralize(debate.viewpoints.size, "vupnt"), debate_url(debate) %>
          </div>

        <% end %>
      <% end %>

    </div>

  </div>

app/views/shared/_error_messages.mobile.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb

<% if @feed_items.any? %>

	<div class="section-title">
		recent updates!
	</div>

	<ol class="debates">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>

<div class="center"><%= will_paginate @feed_items %></div>

<% end %>

app/views/shared/_feed.mobile.erb

<% if @feed_items.any? %>

	<div class="section-title">
		recent updates!
	</div>
	<ol class="debates">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>

<%= will_paginate @feed_items, page_links: false, class: "my_pagination" %>

<% end %>

app/views/shared/_feed_item.html.erb
<div class="container">
<div class="row-fluid">
<div class="span12 offset1">

<li id="<%= feed_item.id %>">
  <div class="user">
    <h2><%= link_to feed_item.user.name, user_path(feed_item.user) %></h2>
  </div>
  <div class="content">
    <%= wrap(feed_item.content) %>
  </div>
  <span class="timestamp">
    updated <%= time_ago_in_words(feed_item.updated_at) %> ago.
  </span>

  <%= render partial: 'shared/win_loss_positions', locals: {debate: feed_item} %>


  <div class="actions">
    <div class="listview">
      <%= link_to pluralize(feed_item.viewpoints.published.size, "vupnt"), debate_url(feed_item) %>
    </div>
  </div>
</li>

</div>
</div>
</div>

app/views/shared/_feed_item.mobile.erb

<li id="<%= feed_item.id %>" style="background:#FFFFCC">
  <h2><%= link_to feed_item.user.name.downcase, user_path(feed_item.user) %></h2>

  <%= render partial: 'shared/debate_content', locals: {debate: feed_item} %>

  <%= render partial: 'shared/win_loss_positions', locals: {debate: feed_item} %>

  <%= render partial: 'shared/debate_item_actions', locals: {
      debate: feed_item, user: feed_item.user
      } %>
</li>

<br />

app/views/shared/_old_viewpoints_item.mobile.erb
  <li id="<%= viewpoints_item.id %>">
      <% cache "sha_vie_ite_1-#{viewpoints_item.id}-#{viewpoints_item.updated_at.to_i}" do %>
        <div class="user">
          <h2><%=link_to viewpoints_item.user.name, viewpoints_item.user %></h2>
        </div>
        <div class="content">
          <%= wrap(viewpoints_item.desc) %>
        </div>
        <span class="timestamp">
          updated <%= time_ago_in_words(viewpoints_item.updated_at) %> ago.
        </span>
      <% end %>
      
      <div class="actions">
        <% if !viewpoints_item.published? %>
          <% if current_user?(viewpoints_item.debate.user) %>
              <div class="publish">
                <%= link_to "publish", publish_path(viewpoints_item), method: :put%>
              </div>
          <% end %>
        <% else %>
          <% cache "sha_vie_ite_2-#{viewpoints_item.id}" do %>
            <div class="voteup">
              <%= link_to "vote it up!", new_argument_path(viewpoint: viewpoints_item, is_up_vote: "") %>
              </div>
        
            <div class="votedown">
              <%= link_to "vote it down!", new_argument_path(viewpoint: viewpoints_item) %>
            </div>

            <div class="listview">
              <%= link_to "arguments", arguments_path(viewpoint: viewpoints_item) %>
            </div>
          <% end %>
        <% end %>

        <!-- the delete option goes here -->

        
      </div>
    </li>

    <br />



app/views/shared/_stats.mobile.erb
<% @user ||= current_user %>
<div class="stats center">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      following: <%= @user.followed_users.count %>
    </strong>

  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      followers: <%= @user.followers.count %>
    </strong>
  </a>


</div>

app/views/shared/_viewpoint_form.mobile.erb

<div class="section-title">
	what's your vupnt?
</div>

<%= form_for(@viewpoint) do |f| %>

    <%= f.text_area :desc, rows: 2 %>
	<%= f.hidden_field :debate_id, value: @debate.id %>
 	<%= f.hidden_field :user_id, value: current_user.id %>
 	
  	<% if @current_user_can_add %>
  		<%= f.hidden_field :published, value: true %>
	<% else %>
		<%= f.hidden_field :published, value: false %>
	<% end %>

	<div class="field-desc">
	share your view in 140 characters or less! 
	</div>

	<div class="center">
  		<%= f.submit "share", class: "btn btn-large btn-primary" %>
	</div>

<% end %>

app/views/shared/_viewpoints.mobile.erb
<% if @viewpoints.any? %>
	<div class="section-title">
    	vupnts...
	</div>
  
  	<ol class="debates">
    	<%= render partial: 'shared/viewpoints_item', collection: @viewpoints %>
  	</ol>
  	
  	<%= will_paginate @viewpoints, page_links: false, class: "my_pagination" %>

<% else %>
	<% if current_user != @user %>
		<div class="alert">
			<%= "#{@user.name.downcase} has not posted any vupnts on this conversation!" %>
		</div>
	<% end %>
<% end %>

app/views/shared/_viewpoints_item.mobile.erb
  <li id="<%= viewpoints_item.id %>">
      <% cache "sha_vie_ite_1-#{viewpoints_item.id}-#{viewpoints_item.updated_at.to_i}" do %>
        <div class="user">
          <h2><%=link_to viewpoints_item.user.name, viewpoints_item.user %></h2>
        </div>
        <div class="content">
          <%= wrap(viewpoints_item.desc) %>
        </div>
        <span class="timestamp">
          updated <%= time_ago_in_words(viewpoints_item.updated_at) %> ago.
        </span>
      <% end %>
      
      <div class="actions">
        <% if !viewpoints_item.published? %>
          <% if current_user?(viewpoints_item.debate.user) %>
              <div class="publish">
                <%= link_to "publish", publish_path(viewpoints_item), method: :put%>
              </div>
          <% end %>
        <% else %>
          <% cache "sha_vie_ite_2-#{viewpoints_item.id}" do %>
            <div class="voteup">
              <%= link_to "vote it up!", new_argument_path(viewpoint: viewpoints_item, is_up_vote: "") %>
              </div>
        
            <div class="votedown">
              <%= link_to "vote it down!", new_argument_path(viewpoint: viewpoints_item) %>
            </div>

            <div class="listview">
              <%= link_to "arguments", arguments_path(viewpoint: viewpoints_item) %>
            </div>
          <% end %>
        <% end %>

        <!-- the delete option goes here -->

        
      </div>
    </li>

    <br />



app/views/shared/_win_loss_positions.mobile.erb
<% leading_view = get_leading_view(debate) %>
<% if leading_view %>
  	<div>
        <span class="label-green">leading view</span><%= leading_view  %>
	</div>
<% elsif tied_view(debate) %>
  	<div>
        <span class="label">tie</span><%= tied_view  %>
	</div>
<% else %>
  	<div>
        <span class="label-black">unresolved</span>
	</div>
<% end %>