config/routes.rb
Vupoint::Application.routes.draw do

  
  get "invitations/new"

  get "invitations/create"

  get "invitations/destroy"

  match 'users/notifications', to: 'users#notifications', as: :notifications

  match 'users/join/:id', to: 'users#join_private_conversation', as: :join_private_conversation 

  resources :users do
    member do
      get :following, :followers
    end
  end

  
  resources :invitation_requests, only: [:new, :create, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]

  resources :debates, only: [:create, :destroy, :show, :index]

  match 'debates/invitation/:id', to: 'debates#invitation', as: :invitation

  match "debates/:id/:url", to: "debates#show"
  
  match "debates/search", to: 'debates#search'

  resources :relationships, only: [:create, :destroy]

  resources :viewpoints, only: [:create, :destroy]

  resources :arguments, only: [:new, :create, :destroy, :index]

  resources :debate_invites, only: [:create, :destroy]

  match 'conversation/allow/:id', to: "debates#allow_joining_private_conversation", as: :allow_joining_private_conversation

  resources :notifications, only: :destroy

  resources :invitations, only: [:new, :create, :destroy]

  root to: 'pages#home'

  match "/help", to: 'pages#help', as: :help

  match "/tou", to: 'pages#tou', as: :terms

  match "/signup", to: 'users#new', as: :signup

  match "/signin", to: 'sessions#new', as: :signin

  match "/signout", to: 'sessions#destroy', as: :signout, via: :delete

  match "/confirm", to: 'users#confirm', as: :confirmation

  match "/invited", to: 'users#invited', as: :invited

  match "/users/search_by_name", to: 'users#search_by_name'

  match "viewpoints/publish/:id", to: 'viewpoints#publish', as: :publish, via: :put

  match 'users/:id/:url', to: "users#show"

  match '/send_invitation', to: "users#send_invitation", as: :send_invitation

  match '/stats', to: "pages#stats", as: :stats 

end

app/views/pages/help.mobile.erb
<h1>help</h1>
<h2>... is on its way!</h2>

app/views/pages/home.html.erb
<div class="center">
  	<h1>
  		your view counts!
  	</h1>
  	<h2>
  		what's your view? say. share. discuss.  
  	</h2>
	<div class="content">
		vupnt is currently available only from a mobile browser!
	</div>

	<div class="btn btn-large">
		<%= link_to "view mobile site", :mobile => 1  %>
	</div>
  
</div>

<div>
    <%= render 'shared/feed' %>
</div>

app/views/pages/home.mobile.erb
<div id="top">
</div>
<% if signed_in? %>
    <% if @has_new_notifications %>
      <div>
        <h2>
          you have <%= link_to "new notifications", notifications_path(current_user) %><%= image_tag("alert.png")%>
        </h2>
      </div>
    <% end %>


  <div class="content">
    <small>
      start a <a href="#new_debate_form">new conversation</a>, or check out some recent ones. and there's <a href="#more_menu">more</a>...
    </small>
  </div>

  <div>
    <%= render 'shared/feed' %>
  </div>

  <div id="new_debate_form">
    <%= render 'shared/debate_form' %>
  </div>

  <% cache "more-stuff-home" do %>
    <div class="section-title", id="more_menu">
      more stuff...
    </div>

    <h2><%= link_to "notifications", notifications_url %> | <%= link_to "conversations", debates_path %> | <%= link_to "people", users_path %> | <%= link_to "invite a friend", new_invitation_path %></h2>
    <hr />

    <h2><a href="#top">top of page</a></h2>
  <% end %>      

<% else %>

<% cache "sign-up-sign-in" do %>

  <div class="center" id="sign">
    	<h1>
    		your view counts!
    	</h1>
    	
      <h2>
    		what's your view? say. share. discuss.  
    	</h2>
      
      <%= link_to "sign up", signup_path, class: "btn btn-large btn-primary" %>

    	<%= link_to "sign in", signin_path, class: "btn btn-large btn-primary" %>

  </div>
<% end %>

<% end %>

app/views/pages/stats.mobile.erb
<div class="section-title">
	user registrations (<%= @user_count_total %>)
</div>
<h2>
	last 24 hrs: <%= @user_count_24_hrs_1 %>
</h2>
<h2>
	last 48-24 hrs: <%= @user_count_24_hrs_2 %>
</h2>
<h2>
	last 72-48 hrs: <%= @user_count_24_hrs_3 %>
</h2>

<div class="section-title">
	new debates (<%= @debate_count_total %>)
</div>
<h2>
	last 24 hrs: <%= @debate_count_24_hrs_1 %>
</h2>
<h2>
	last 48-24 hrs: <%= @debate_count_24_hrs_2 %>
</h2>
<h2>
	last 72-48 hrs: <%= @debate_count_24_hrs_3 %>
</h2>

<div class="section-title">
	new viewpoints (<%= @viewpoint_count_total %>)
</div>
<h2>
	last 24 hrs: <%= @viewpoint_count_24_hrs_1 %>
</h2>
<h2>
	last 48-24 hrs: <%= @viewpoint_count_24_hrs_2 %>
</h2>
<h2>
	last 72-48 hrs: <%= @viewpoint_count_24_hrs_3 %>
</h2>

<div class="section-title">
	new arguments (<%= @argument_count_total %>)
</div>
<h2>
	last 24 hrs: <%= @argument_count_24_hrs_1 %>
</h2>
<h2>
	last 48-24 hrs: <%= @argument_count_24_hrs_2 %>
</h2>
<h2>
	last 72-48 hrs: <%= @argument_count_24_hrs_3 %>
</h2>

app/views/pages/tou.mobile.erb
<h1>terms of use</h1>
<h2>you agree to be good and nice to others, even while being critical! be humble. have an open mind. and do not break any law of the land. you agree that your right to a viewpoint ends where the others' right to have their own begins! have fun. keep coming back to read these terms of use as they may change without notice (the 'have fun' part will stay!)</h2>