config/routes.rb
Vupoint::Application.routes.draw do

  
  get "invitations/new"

  get "invitations/create"

  get "invitations/destroy"

  match 'users/notifications', to: 'users#notifications', as: :notifications

  match 'users/join/:id', to: 'users#join_private_conversation', as: :join_private_conversation 

  resources :users do
    member do
      get :following, :followers
    end
  end

  
  resources :invitation_requests, only: [:new, :create, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]

  resources :debates, only: [:create, :destroy, :show, :index]

  match 'debates/invitation/:id', to: 'debates#invitation', as: :invitation

  match "debates/:id/:url", to: "debates#show"
  
  match "debates/search", to: 'debates#search'

  resources :relationships, only: [:create, :destroy]

  resources :viewpoints, only: [:create, :destroy]

  resources :arguments, only: [:new, :create, :destroy, :index]

  resources :debate_invites, only: [:create, :destroy]

  match 'conversation/allow/:id', to: "debates#allow_joining_private_conversation", as: :allow_joining_private_conversation

  resources :notifications, only: :destroy

  resources :invitations, only: [:new, :create, :destroy]

  root to: 'pages#home'

  match "/help", to: 'pages#help', as: :help

  match "/tou", to: 'pages#tou', as: :terms

  match "/signup", to: 'users#new', as: :signup

  match "/signin", to: 'sessions#new', as: :signin

  match "/signout", to: 'sessions#destroy', as: :signout, via: :delete

  match "/confirm", to: 'users#confirm', as: :confirmation

  match "/invited", to: 'users#invited', as: :invited

  match "/users/search_by_name", to: 'users#search_by_name'

  match "viewpoints/publish/:id", to: 'viewpoints#publish', as: :publish, via: :put

  match 'users/:id/:url', to: "users#show"

  match '/send_invitation', to: "users#send_invitation", as: :send_invitation

  match '/stats', to: "pages#stats", as: :stats 

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to image_tag("home.png", alt: "home"), root_path %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "mobile site", :mobile => 1 %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_footer.mobile.erb
<footer class="footer">
  <% cache "home-icon" do %>
    <small>
      <%= link_to image_tag("home.png", alt: "home"), root_path %>
    </small>
  <% end %>
  <nav>
    <ul>
      <% if signed_in? %>
        <% if !current_user.confirmed_at %>
          <li><%= link_to "confirm email", '#' %></li>
        <% end %>

        <% if current_user.admin %>
          <li><%= link_to "stats", stats_path %></li>
        <% end %>
        
      <li><%= link_to "sign out", signout_path, method: "delete" %></li>
      <% end %>
      <li><%= link_to "help", help_path %></li>
      <li><%= link_to "terms", terms_path %></li>

    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(@title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "mobile" if mobile_device? %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
   <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
  <header>
    <div class="navbar">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <%= link_to "vupnt", root_path, class: "brand" %>

        </div>
      </div>
    </div>
  </header>
  <div class="container-fluid">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
  <title><%= full_title(@title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "mobile" if mobile_device? %>
  <%= javascript_include_tag "application" %>
  <meta name="HandheldFriendly" content="True"/>
   <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
  <%= csrf_meta_tags %>
   <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  <% cache "share-this-script" do %>
  <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
  <script type="text/javascript">
    stLight.options({
      publisher: "a66dd7f9-95a1-4b89-a7b8-5d229f4d44af"
      });
  </script>
  <% end %>
  
</head>
<body>


<header>
    <div class="navbar">
      <div class="navbar-inner">
        <div class="container-fluid">
          
          <%= link_to "VUpnt", root_path, class: "brand" %>

          <% if signed_in? %>
            <div class="btn-group pull-right">
              <%= link_to current_user.name.downcase, user_path(current_user), class: "btn btn-primary" %>
            </div>
          <% end %>

        </div>
      </div>
    </div>
</header>



  <div class="container-fluid">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>


    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>